# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gtexswifi/setup-makefiles.sh

# Proprietary blobs for Android 9 - 32-bit WiFi-only
PRODUCT_COPY_FILES += \
    vendor/samsung/gtexswifi/proprietary/bin/batterysrv:$(TARGET_COPY_OUT_SYSTEM)/bin/batterysrv \
    vendor/samsung/gtexswifi/proprietary/bin/calibration_init:$(TARGET_COPY_OUT_SYSTEM)/bin/calibration_init \
    vendor/samsung/gtexswifi/proprietary/bin/charge:$(TARGET_COPY_OUT_SYSTEM)/bin/charge \
    vendor/samsung/gtexswifi/proprietary/bin/connfwexe:$(TARGET_COPY_OUT_SYSTEM)/bin/connfwexe \
    vendor/samsung/gtexswifi/proprietary/bin/ddexe:$(TARGET_COPY_OUT_SYSTEM)/bin/ddexe \
    vendor/samsung/gtexswifi/proprietary/bin/download:$(TARGET_COPY_OUT_SYSTEM)/bin/download \
    vendor/samsung/gtexswifi/proprietary/bin/drsd:$(TARGET_COPY_OUT_SYSTEM)/bin/drsd \
    vendor/samsung/gtexswifi/proprietary/bin/engpc:$(TARGET_COPY_OUT_SYSTEM)/bin/engpc \
    vendor/samsung/gtexswifi/proprietary/bin/ext_symlink.sh:$(TARGET_COPY_OUT_SYSTEM)/bin/ext_symlink.sh \
    vendor/samsung/gtexswifi/proprietary/bin/macloader:$(TARGET_COPY_OUT_SYSTEM)/bin/macloader \
    vendor/samsung/gtexswifi/proprietary/bin/mfgloader:$(TARGET_COPY_OUT_SYSTEM)/bin/mfgloader \
    vendor/samsung/gtexswifi/proprietary/bin/wcnd:$(TARGET_COPY_OUT_SYSTEM)/bin/wcnd \
    vendor/samsung/gtexswifi/proprietary/bin/wlandutservice:$(TARGET_COPY_OUT_SYSTEM)/bin/wlandutservice \
    vendor/samsung/gtexswifi/proprietary/cameradata/datapattern_420sp.yuv:$(TARGET_COPY_OUT_SYSTEM)/cameradata/datapattern_420sp.yuv \
    vendor/samsung/gtexswifi/proprietary/cameradata/datapattern_front_420sp.yuv:$(TARGET_COPY_OUT_SYSTEM)/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/gtexswifi/proprietary/etc/HARRIER_ASIC_PATCH.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/HARRIER_ASIC_PATCH.bin \
    vendor/samsung/gtexswifi/proprietary/etc/ca.pem:$(TARGET_COPY_OUT_SYSTEM)/etc/ca.pem \
    vendor/samsung/gtexswifi/proprietary/etc/connectivity_calibration.ini:$(TARGET_COPY_OUT_SYSTEM)/etc/connectivity_calibration.ini \
    vendor/samsung/gtexswifi/proprietary/etc/connectivity_configure.ini:$(TARGET_COPY_OUT_SYSTEM)/etc/connectivity_configure.ini \
    vendor/samsung/gtexswifi/proprietary/etc/firmware/sc2331_fdl.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sc2331_fdl.bin \
    vendor/samsung/gtexswifi/proprietary/etc/firmware/sc2331_fw.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sc2331_fw.bin \
    vendor/samsung/gtexswifi/proprietary/etc/thermalSensorsConfig.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/thermalSensorsConfig.xml \
    vendor/samsung/gtexswifi/proprietary/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/gtexswifi/proprietary/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/gtexswifi/proprietary/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/gtexswifi/proprietary/lib/hw/camera.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.sc8830.so \
    vendor/samsung/gtexswifi/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.default.so \
    vendor/samsung/gtexswifi/proprietary/lib/hw/sensors.sc8830.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.sc8830.so \
    vendor/samsung/gtexswifi/proprietary/lib/libAF.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAF.so \
    vendor/samsung/gtexswifi/proprietary/lib/libAl_Awb_v2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb_v2.so \
    vendor/samsung/gtexswifi/proprietary/lib/libQjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libQjpeg.so \
    vendor/samsung/gtexswifi/proprietary/lib/libQmageDecoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libQmageDecoder.so \
    vendor/samsung/gtexswifi/proprietary/lib/lib_SamsungRec_V04013.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SamsungRec_V04013.so \
    vendor/samsung/gtexswifi/proprietary/lib/lib_Samsung_Resampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_Samsung_Resampler.so \
    vendor/samsung/gtexswifi/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v04004.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_Samsung_SB_AM_for_ICS_v04004.so \
    vendor/samsung/gtexswifi/proprietary/lib/libae.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libae.so \
    vendor/samsung/gtexswifi/proprietary/lib/libaf_running.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaf_running.so \
    vendor/samsung/gtexswifi/proprietary/lib/libaf_tune.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaf_tune.so \
    vendor/samsung/gtexswifi/proprietary/lib/libawb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbm.so \
    vendor/samsung/gtexswifi/proprietary/lib/libboost.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libboost.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbt-aptx-4.0.3.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-aptx-4.0.3.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbt-codec_aptx.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-codec_aptx.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbt-codec_sshd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-codec_sshd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbt-iopdb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-iopdb.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbt-iopdb_mod.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-iopdb_mod.so \
    vendor/samsung/gtexswifi/proprietary/lib/libbt-vendor.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-vendor.so \
    vendor/samsung/gtexswifi/proprietary/lib/libcalibration.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcalibration.so \
    vendor/samsung/gtexswifi/proprietary/lib/libcc_manager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcc_manager.so \
    vendor/samsung/gtexswifi/proprietary/lib/libcharon.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcharon.so \
    vendor/samsung/gtexswifi/proprietary/lib/libcrptoo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcrptoo.so \
    vendor/samsung/gtexswifi/proprietary/lib/libdeflicker.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdeflicker.so \
    vendor/samsung/gtexswifi/proprietary/lib/libedmnativehelper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libedmnativehelper.so \
    vendor/samsung/gtexswifi/proprietary/lib/libefuse.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libefuse.so \
    vendor/samsung/gtexswifi/proprietary/lib/libengbt.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libengbt.so \
    vendor/samsung/gtexswifi/proprietary/lib/libfactoryutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfactoryutil.so \
    vendor/samsung/gtexswifi/proprietary/lib/libgpspc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgpspc.so \
    vendor/samsung/gtexswifi/proprietary/lib/libhydra.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhydra.so \
    vendor/samsung/gtexswifi/proprietary/lib/libicuoc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libicuoc.so \
    vendor/samsung/gtexswifi/proprietary/lib/libiwnpi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libiwnpi.so \
    vendor/samsung/gtexswifi/proprietary/lib/liblsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liblsc.so \
    vendor/samsung/gtexswifi/proprietary/lib/libmaet.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmaet.so \
    vendor/samsung/gtexswifi/proprietary/lib/libmemoryheapion.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmemoryheapion.so \
    vendor/samsung/gtexswifi/proprietary/lib/libnvexchange.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvexchange.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomission_avoidance.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomission_avoidance.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_aacdec_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_aacdec_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_avcdec_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_avcdec_sw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_avcenc_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_mp3dec_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libomx_vpxdec_hw_sprd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/gtexswifi/proprietary/lib/libool.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libool.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsamsungRecord.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungRecord.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsamsungSoundbooster.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungSoundbooster.so \
    vendor/samsung/gtexswifi/proprietary/lib/libseccamera_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libseccamera_jni.so \
    vendor/samsung/gtexswifi/proprietary/lib/libseccameracore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libseccameracore.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsecnativefeature.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsecure_storage.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsecure_storage.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsft_af_ctrl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsft_af_ctrl.so \
    vendor/samsung/gtexswifi/proprietary/lib/libspaf.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libspaf.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsprdlsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsprdlsc.so \
    vendor/samsung/gtexswifi/proprietary/lib/libstlport.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstlport.so \
    vendor/samsung/gtexswifi/proprietary/lib/libstrongswan.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstrongswan.so \
    vendor/samsung/gtexswifi/proprietary/lib/libsxqk_skia.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsxqk_skia.so \
    vendor/samsung/gtexswifi/proprietary/lib/libvbeffect.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvbeffect.so \
    vendor/samsung/gtexswifi/proprietary/lib/libvbpga.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvbpga.so \
    vendor/samsung/gtexswifi/proprietary/lib/libwrappergps.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwrappergps.so \
    vendor/samsung/gtexswifi/proprietary/lib/libynoise.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libynoise.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/libWVphoneAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVphoneAPI.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/gtexswifi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so

# 32-bit prebuilt modules (WiFi-only - no RIL)
PRODUCT_PACKAGES += \
    libwrappergps \
    libbt-vendor \
    libsecnativefeature

# WiFi properties
PRODUCT_PROPERTY_OVERRIDES += \
    wifi.interface=wlan0 \
    wifi.direct.interface=p2p0 \
    ro.wifi.channels=

# Bluetooth properties
PRODUCT_PROPERTY_OVERRIDES += \
    ro.bluetooth.dun=true \
    ro.bluetooth.hfp.ver=1.6 \
    ro.bluetooth.sap=true \
    ro.bt.bdaddr_path=/efs/bluetooth/bt_addr

# GPS properties
PRODUCT_PROPERTY_OVERRIDES += \
    ro.kernel.android.gps=ttyS1 \
    ro.kernel.android.gps.speed=9600

# WiFi-only device (no telephony)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.carrier=wifi-only \
    ro.radio.noril=true \
    persist.sys.force_sw_gles=1

# Widevine DRM properties
PRODUCT_PROPERTY_OVERRIDES += \
    drm.service.enabled=true
